services:
  - type: web
    name: upi-discord-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: MONGO_URI
        sync: false
      - key: ENCRYPTION_KEY
        sync: false
    healthCheckPath: /health
    autoDeploy: true
